global:
  resolve_timeout: 5m
  slack_api_url: https://hooks.slack.com/services/XXXXXXXX/YYYYYYYY/aaaaaaaaaaaaaaaaaa

route:
  group_by: ['alertname', 'group']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1d
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true
        channel: '#general'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

