{
 "title": "Raspberry Pi",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "query": "label_values(up, instance)" }
  ]
 },
 "panels": [
  {
   "title": "ICMP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sum without(mode) (rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$server:9100\"}[2m])))",
     "legendFormat": "{{instance}}({{cpu}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$server:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$server:9100\"}) / node_memory_MemTotal_bytes{instance=~\"$server:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$server:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$server:9100\"} - node_boot_time_seconds{instance=~\"$server:9100\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without(mode)(rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$server:9100\"}[2m]))",
     "legendFormat": "CPU{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage by mode)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without(cpu) (rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$server:9100\"}[2m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$server:9100\"} - node_memory_SwapFree_bytes{instance=~\"$server:9100\"}) / node_memory_SwapTotal_bytes{instance=~\"$server:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}