{
 "title": "Rasberry pi",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(up, instance)" } }
  ]
 },
 "panels": [
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum without(mode) (rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$server:9100\"}[2m])))",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$server:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$server:9100\"}) / node_memory_MemTotal_bytes{instance=~\"$server:9100\"}",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server:9100\"}"
    }
   ]
  },
  {
   "title": "Server up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$server:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$server:9100\"} - node_boot_time_seconds{instance=~\"$server:9100\"}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:9100\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$server:9100\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$server:9100\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Current Load Average (1m)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:9100\"}"
    }
   ]
  },
  {
   "title": "Current Load Average (5m)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=~\"$server:9100\"}"
    }
   ]
  },
  {
   "title": "Current Load Average (15m)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{instance=~\"$server:9100\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without(mode)(rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$server:9100\"}[2m]))",
     "legendFormat": "CPU{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage by mode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without(cpu) (rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$server:9100\"}[2m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Usage (user)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(cpu) (rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$server:9100\"}[2m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server:9100\"}",
     "legendFormat": "Memory Size"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$server:9100\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Current Memory Usage (Bytes)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$server:9100\"}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$server:9100\"} - node_memory_SwapFree_bytes{instance=~\"$server:9100\"}) / node_memory_SwapTotal_bytes{instance=~\"$server:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$server:9100\"}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Disk Use Rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$server:9100\",fstype!=\"tmpfs\"} - node_filesystem_avail_bytes{instance=\"$server:9100\",fstype!=\"tmpfs\"}) / node_filesystem_size_bytes{instance=\"$server:9100\",fstype!=\"tmpfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$server:9100\"}[2m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O Bytes (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$server:9100\"}[2m])",
     "legendFormat": "{{device}} (read)"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$server:9100\"}[2m])",
     "legendFormat": "{{device}} (write)"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server:9100\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Network Transimission Volume (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$server:9100\",device=~\"(eth|wlan|docker)[0-9]+\"}[2m])",
     "legendFormat": "{{device}}(receive)"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$server:9100\",device=~\"(eth|wlan|docker)[0-9]+\"}[2m])",
     "legendFormat": "{{device}}(transmit)"
    }
   ]
  },
  {
   "title": "TCP Connection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server:9100\", state!~\".*bytes\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Network Drop",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{instance=~\"$server:9100\", device!='lo'}[2m])",
     "legendFormat": "{{device}} (receive)"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{instance=~\"$server:9100\", device!='lo'}[2m])",
     "legendFormat": "{{device}} (transmit)"
    }
   ]
  },
  {
   "title": "TCP RetransSegs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"$server:9100\"}[2m])",
     "legendFormat": "TCP RetransSegs"
    }
   ]
  },
  { "title": "File descriptor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "File descriptor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=~\"$server:9100\"}",
     "legendFormat": "max"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"$server:9100\"}",
     "legendFormat": "alocated"
    }
   ]
  }
 ]
}